// <auto-generated />
namespace Training.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class assignement_extend_with_course : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(assignement_extend_with_course));
        
        string IMigrationMetadata.Id
        {
            get { return "202302271328142_assignement_extend_with_course"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
