// <auto-generated />
namespace Training.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class schoolmap_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(schoolmap_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202302160947268_schoolmap_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
